// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyUglyRocks.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyUglyRocks.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251130211359_M2CoreTracking")]
    partial class M2CoreTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyUglyRocks.Core.Entities.Barrel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("BarrelNumber")
                        .HasColumnType("integer")
                        .HasColumnName("barrel_number");

                    b.Property<decimal?>("Capacity")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("capacity");

                    b.Property<string>("ContaminationNotes")
                        .HasColumnType("text")
                        .HasColumnName("contamination_notes");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DateLastDeepClean")
                        .HasColumnType("date")
                        .HasColumnName("date_last_deep_clean");

                    b.Property<DateTime>("DateUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated")
                        .HasDefaultValueSql("now()");

                    b.PrimitiveCollection<string[]>("DedicatedStages")
                        .HasColumnType("varchar(100)[]")
                        .HasColumnName("dedicated_stages");

                    b.Property<decimal?>("DefaultGritAmountGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("default_grit_amount_grams");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCapacityMetric")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_capacity_metric");

                    b.Property<bool>("IsDedicated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_dedicated");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nickname");

                    b.Property<Guid>("TumblerId")
                        .HasColumnType("uuid")
                        .HasColumnName("tumbler_id");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_barrels_is_active");

                    b.HasIndex("TumblerId")
                        .HasDatabaseName("ix_barrels_tumbler_id");

                    b.ToTable("barrels", (string)null);
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.BarrelNickname", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DateUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uuid")
                        .HasColumnName("user_created");

                    b.Property<Guid?>("UserUpdated")
                        .HasColumnType("uuid")
                        .HasColumnName("user_updated");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_barrel_nicknames_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_barrel_nicknames_name");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("barrel_nicknames", (string)null);
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.CleaningMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("AmountGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount_grams");

                    b.Property<decimal?>("AmountMilliliters")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount_milliliters");

                    b.Property<Guid>("CleaningRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("cleaning_run_id");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DateUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("DisplayAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("display_amount");

                    b.Property<string>("DisplayUnit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("display_unit");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("CleaningRunId")
                        .HasDatabaseName("ix_cleaning_materials_cleaning_run_id");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("ix_cleaning_materials_material_id");

                    b.ToTable("cleaning_materials", (string)null);
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.CleaningRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DateReminderSent")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_reminder_sent");

                    b.Property<DateTime>("DateUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.Property<bool>("ReminderEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("reminder_enabled");

                    b.Property<string>("ResultNotes")
                        .HasColumnType("text")
                        .HasColumnName("result_notes");

                    b.Property<Guid>("StageRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("stage_run_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("StageRunId")
                        .IsUnique()
                        .HasDatabaseName("ix_cleaning_runs_stage_run_id");

                    b.ToTable("cleaning_runs", (string)null);
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.Cycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AdditionalSpecimens")
                        .HasColumnType("text")
                        .HasColumnName("additional_specimens");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_deleted");

                    b.Property<DateTime>("DateUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DifficultyRating")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty_rating");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int?>("FinalQuality")
                        .HasColumnType("integer")
                        .HasColumnName("final_quality");

                    b.Property<string>("Goal")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("goal");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("ix_cycles_start_date");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_cycles_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_cycles_user_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_cycles_user_id_status");

                    b.ToTable("cycles", (string)null);
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.CycleSpecimen", b =>
                {
                    b.Property<Guid>("CycleId")
                        .HasColumnType("uuid")
                        .HasColumnName("cycle_id");

                    b.Property<Guid>("SpecimenId")
                        .HasColumnType("uuid")
                        .HasColumnName("specimen_id");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DateUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CycleId", "SpecimenId");

                    b.HasIndex("SpecimenId")
                        .HasDatabaseName("ix_cycle_specimens_specimen_id");

                    b.ToTable("cycle_specimens", (string)null);
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("common_name");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DateUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCleaning")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_cleaning");

                    b.Property<string>("MaterialSize")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("material_size");

                    b.Property<string>("MaterialType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material_type");

                    b.Property<int>("MeshSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("mesh_size");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<int?>("UsageType")
                        .HasColumnType("integer")
                        .HasColumnName("usage_type");

                    b.Property<Guid>("UserCreated")
                        .HasColumnType("uuid")
                        .HasColumnName("user_created");

                    b.Property<Guid>("UserUpdated")
                        .HasColumnType("uuid")
                        .HasColumnName("user_updated");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_materials_category");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_materials_is_active");

                    b.HasIndex("IsCleaning")
                        .HasDatabaseName("ix_materials_is_cleaning");

                    b.HasIndex("UserCreated");

                    b.HasIndex("UserUpdated");

                    b.ToTable("materials", (string)null);
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_deleted");

                    b.Property<DateTime>("DateUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mime_type");

                    b.Property<int>("PhotoType")
                        .HasColumnType("integer")
                        .HasColumnName("photo_type");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<Guid>("StageRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("stage_run_id");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("PhotoType")
                        .HasDatabaseName("ix_photos_photo_type");

                    b.HasIndex("StageRunId")
                        .HasDatabaseName("ix_photos_stage_run_id");

                    b.ToTable("photos", (string)null);
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DateExpires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_expires");

                    b.Property<DateTime?>("DateRevoked")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_revoked");

                    b.Property<DateTime>("DateUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("device_info");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DateExpires")
                        .HasDatabaseName("ix_refresh_tokens_date_expires");

                    b.HasIndex("ReplacedByTokenId");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.Specimen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Alias")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("alias");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("common_name");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DateUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("MaterialType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("material_type");

                    b.Property<decimal?>("MohsHardnessMax")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("mohs_hardness_max");

                    b.Property<decimal?>("MohsHardnessMin")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("mohs_hardness_min");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("RecommendedGritSequence")
                        .HasColumnType("text")
                        .HasColumnName("recommended_grit_sequence");

                    b.Property<string>("RockFamily")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rock_family");

                    b.Property<string>("ScientificName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scientific_name");

                    b.Property<string>("SpecialConsiderations")
                        .HasColumnType("text")
                        .HasColumnName("special_considerations");

                    b.Property<string>("Species")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("species");

                    b.Property<int?>("TumblingDifficulty")
                        .HasColumnType("integer")
                        .HasColumnName("tumbling_difficulty");

                    b.Property<Guid>("UserCreated")
                        .HasColumnType("uuid")
                        .HasColumnName("user_created");

                    b.Property<Guid>("UserUpdated")
                        .HasColumnType("uuid")
                        .HasColumnName("user_updated");

                    b.Property<string>("Variety")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("variety");

                    b.HasKey("Id");

                    b.HasIndex("CommonName")
                        .HasDatabaseName("ix_specimens_common_name");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_specimens_is_active");

                    b.HasIndex("UserCreated")
                        .HasDatabaseName("ix_specimens_user_created");

                    b.HasIndex("UserUpdated");

                    b.ToTable("specimens", (string)null);
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.StageMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("AmountGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount_grams");

                    b.Property<decimal?>("AmountMilliliters")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount_milliliters");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DateUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("DisplayAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("display_amount");

                    b.Property<string>("DisplayUnit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("display_unit");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<Guid>("StageRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("stage_run_id");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("ix_stage_materials_material_id");

                    b.HasIndex("StageRunId")
                        .HasDatabaseName("ix_stage_materials_stage_run_id");

                    b.ToTable("stage_materials", (string)null);
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.StageRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BarrelId")
                        .HasColumnType("uuid")
                        .HasColumnName("barrel_id");

                    b.Property<decimal?>("BarrelRpm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("barrel_rpm");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uuid")
                        .HasColumnName("cycle_id");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_deleted");

                    b.Property<DateTime?>("DateReminderSent")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_reminder_sent");

                    b.Property<DateTime>("DateUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DurationDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("duration_days");

                    b.Property<int>("DurationHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("duration_hours");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date_time");

                    b.Property<int?>("FillLevelPercent")
                        .HasColumnType("integer")
                        .HasColumnName("fill_level_percent");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool?>("IsRpmEstimated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_rpm_estimated");

                    b.Property<bool?>("IssueChips")
                        .HasColumnType("boolean")
                        .HasColumnName("issue_chips");

                    b.Property<bool?>("IssueContamination")
                        .HasColumnType("boolean")
                        .HasColumnName("issue_contamination");

                    b.Property<bool?>("IssueScratches")
                        .HasColumnType("boolean")
                        .HasColumnName("issue_scratches");

                    b.Property<bool?>("IssueUnderRounded")
                        .HasColumnType("boolean")
                        .HasColumnName("issue_under_rounded");

                    b.Property<string>("LessonsLearned")
                        .HasColumnType("text")
                        .HasColumnName("lessons_learned");

                    b.Property<decimal?>("LoadWeightAfterGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("load_weight_after_grams");

                    b.Property<decimal?>("LoadWeightBeforeGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("load_weight_before_grams");

                    b.Property<int?>("NextAction")
                        .HasColumnType("integer")
                        .HasColumnName("next_action");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("RemindAfterDays")
                        .HasColumnType("integer")
                        .HasColumnName("remind_after_days");

                    b.Property<bool?>("RemindAtEndOfStage")
                        .HasColumnType("boolean")
                        .HasColumnName("remind_at_end_of_stage");

                    b.Property<bool>("ReminderEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("reminder_enabled");

                    b.Property<int?>("ResultPitting")
                        .HasColumnType("integer")
                        .HasColumnName("result_pitting");

                    b.Property<int?>("ResultRating")
                        .HasColumnType("integer")
                        .HasColumnName("result_rating");

                    b.Property<int?>("ResultScratchLevel")
                        .HasColumnType("integer")
                        .HasColumnName("result_scratch_level");

                    b.Property<int?>("ResultShapeRounding")
                        .HasColumnType("integer")
                        .HasColumnName("result_shape_rounding");

                    b.Property<int?>("ResultShine")
                        .HasColumnType("integer")
                        .HasColumnName("result_shine");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stage_name");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date_time");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<int?>("WaterLevel")
                        .HasColumnType("integer")
                        .HasColumnName("water_level");

                    b.HasKey("Id");

                    b.HasIndex("BarrelId")
                        .HasDatabaseName("ix_stage_runs_barrel_id");

                    b.HasIndex("CycleId")
                        .HasDatabaseName("ix_stage_runs_cycle_id");

                    b.HasIndex("EndDateTime")
                        .HasDatabaseName("ix_stage_runs_end_date_time");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_stage_runs_status");

                    b.ToTable("stage_runs", (string)null);
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.Tumbler", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DateUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsGeneric")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_generic");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("TumblerModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("tumbler_model_id");

                    b.Property<int>("TumblerType")
                        .HasColumnType("integer")
                        .HasColumnName("tumbler_type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_tumblers_is_active");

                    b.HasIndex("IsGeneric")
                        .HasDatabaseName("ix_tumblers_is_generic");

                    b.HasIndex("TumblerModelId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tumblers_user_id");

                    b.ToTable("tumblers", (string)null);
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.TumblerModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DateUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DefaultBarrelCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("default_barrel_count");

                    b.Property<decimal?>("DefaultCapacityLbs")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("default_capacity_lbs");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCustomEntry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_custom_entry");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("sort_order");

                    b.Property<int>("TumblerType")
                        .HasColumnType("integer")
                        .HasColumnName("tumbler_type");

                    b.HasKey("Id");

                    b.HasIndex("Brand")
                        .HasDatabaseName("ix_tumbler_models_brand");

                    b.HasIndex("IsActive", "SortOrder")
                        .HasDatabaseName("ix_tumbler_models_is_active_sort_order");

                    b.ToTable("tumbler_models", (string)null);
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DateEmailVerified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_email_verified");

                    b.Property<DateTime?>("DateLastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_last_login");

                    b.Property<DateTime?>("DateOnboardingCompleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_onboarding_completed");

                    b.Property<DateTime?>("DatePasswordChanged")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_password_changed");

                    b.Property<DateTime>("DateUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_attempts");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LockoutEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end_time");

                    b.Property<bool>("OnboardingCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("onboarding_completed");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("role");

                    b.Property<string>("UnlockToken")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("unlock_token");

                    b.Property<DateTime?>("UnlockTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlock_token_expiry");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("LockoutEndTime")
                        .HasDatabaseName("ix_users_lockout_end_time");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("AddWatermark")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("add_watermark");

                    b.Property<bool>("AutoFillFromLastRun")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("auto_fill_from_last_run");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DateFormat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("date_format");

                    b.Property<DateTime>("DateUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DefaultHomeSection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("default_home_section");

                    b.Property<int>("DefaultPostVisibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("default_post_visibility");

                    b.Property<int>("Density")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("density");

                    b.Property<int>("DigestFrequency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("digest_frequency");

                    b.Property<int>("FirstDayOfWeek")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("first_day_of_week");

                    b.Property<int>("FontSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("font_size");

                    b.Property<int>("MeasurementSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("measurement_system");

                    b.Property<bool>("NotifyComments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("notify_comments");

                    b.Property<bool>("NotifyRecipeCloned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("notify_recipe_cloned");

                    b.Property<bool>("NotifyReplies")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("notify_replies");

                    b.Property<bool>("NotifyStageReminders")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("notify_stage_reminders");

                    b.Property<bool>("NotifyUglyRocks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("notify_ugly_rocks");

                    b.Property<int>("PhotoUploadQuality")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("photo_upload_quality");

                    b.Property<bool>("QuietHoursEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("quiet_hours_enabled");

                    b.Property<TimeOnly?>("QuietHoursEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("quiet_hours_end");

                    b.Property<TimeOnly?>("QuietHoursStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("quiet_hours_start");

                    b.Property<bool>("ShowRelativeTimes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("show_relative_times");

                    b.Property<string>("StageFieldVisibility")
                        .HasColumnType("jsonb")
                        .HasColumnName("stage_field_visibility");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("obsidian")
                        .HasColumnName("theme");

                    b.Property<int>("TimeFormat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("time_format");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("UTC")
                        .HasColumnName("timezone");

                    b.Property<int>("TrackingMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tracking_mode");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_settings_user_id");

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.Barrel", b =>
                {
                    b.HasOne("MyUglyRocks.Core.Entities.Tumbler", "Tumbler")
                        .WithMany("Barrels")
                        .HasForeignKey("TumblerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tumbler");
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.BarrelNickname", b =>
                {
                    b.HasOne("MyUglyRocks.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("MyUglyRocks.Core.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.CleaningMaterial", b =>
                {
                    b.HasOne("MyUglyRocks.Core.Entities.CleaningRun", "CleaningRun")
                        .WithMany("CleaningMaterials")
                        .HasForeignKey("CleaningRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyUglyRocks.Core.Entities.Material", "Material")
                        .WithMany("CleaningMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CleaningRun");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.CleaningRun", b =>
                {
                    b.HasOne("MyUglyRocks.Core.Entities.StageRun", "StageRun")
                        .WithOne("CleaningRun")
                        .HasForeignKey("MyUglyRocks.Core.Entities.CleaningRun", "StageRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StageRun");
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.Cycle", b =>
                {
                    b.HasOne("MyUglyRocks.Core.Entities.User", "User")
                        .WithMany("Cycles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.CycleSpecimen", b =>
                {
                    b.HasOne("MyUglyRocks.Core.Entities.Cycle", "Cycle")
                        .WithMany("CycleSpecimens")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyUglyRocks.Core.Entities.Specimen", "Specimen")
                        .WithMany("CycleSpecimens")
                        .HasForeignKey("SpecimenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cycle");

                    b.Navigation("Specimen");
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.Material", b =>
                {
                    b.HasOne("MyUglyRocks.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("UserCreated")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyUglyRocks.Core.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UserUpdated")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.Photo", b =>
                {
                    b.HasOne("MyUglyRocks.Core.Entities.StageRun", "StageRun")
                        .WithMany("Photos")
                        .HasForeignKey("StageRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StageRun");
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("MyUglyRocks.Core.Entities.RefreshToken", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyUglyRocks.Core.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.Specimen", b =>
                {
                    b.HasOne("MyUglyRocks.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("UserCreated")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyUglyRocks.Core.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UserUpdated")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.StageMaterial", b =>
                {
                    b.HasOne("MyUglyRocks.Core.Entities.Material", "Material")
                        .WithMany("StageMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyUglyRocks.Core.Entities.StageRun", "StageRun")
                        .WithMany("StageMaterials")
                        .HasForeignKey("StageRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("StageRun");
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.StageRun", b =>
                {
                    b.HasOne("MyUglyRocks.Core.Entities.Barrel", "Barrel")
                        .WithMany("StageRuns")
                        .HasForeignKey("BarrelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyUglyRocks.Core.Entities.Cycle", "Cycle")
                        .WithMany("StageRuns")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barrel");

                    b.Navigation("Cycle");
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.Tumbler", b =>
                {
                    b.HasOne("MyUglyRocks.Core.Entities.TumblerModel", "TumblerModel")
                        .WithMany("Tumblers")
                        .HasForeignKey("TumblerModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyUglyRocks.Core.Entities.User", "User")
                        .WithMany("Tumblers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TumblerModel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.UserSettings", b =>
                {
                    b.HasOne("MyUglyRocks.Core.Entities.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("MyUglyRocks.Core.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.Barrel", b =>
                {
                    b.Navigation("StageRuns");
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.CleaningRun", b =>
                {
                    b.Navigation("CleaningMaterials");
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.Cycle", b =>
                {
                    b.Navigation("CycleSpecimens");

                    b.Navigation("StageRuns");
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.Material", b =>
                {
                    b.Navigation("CleaningMaterials");

                    b.Navigation("StageMaterials");
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.Specimen", b =>
                {
                    b.Navigation("CycleSpecimens");
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.StageRun", b =>
                {
                    b.Navigation("CleaningRun");

                    b.Navigation("Photos");

                    b.Navigation("StageMaterials");
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.Tumbler", b =>
                {
                    b.Navigation("Barrels");
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.TumblerModel", b =>
                {
                    b.Navigation("Tumblers");
                });

            modelBuilder.Entity("MyUglyRocks.Core.Entities.User", b =>
                {
                    b.Navigation("Cycles");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Settings");

                    b.Navigation("Tumblers");
                });
#pragma warning restore 612, 618
        }
    }
}
