using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MyUglyRocks.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class SeedBadWords : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Seed bad words from docs/seed-data/bad-words-seed.txt
            // This list prevents inappropriate usernames
            var badWords = GetBadWords();

            foreach (var word in badWords)
            {
                // Use parameterized query to prevent SQL injection
                migrationBuilder.Sql(
                    $"INSERT INTO bad_words (word, notes, date_created, date_updated) " +
                    $"VALUES ('{word.Replace("'", "''")}', 'Imported from bad-words-seed.txt', now(), now()) " +
                    $"ON CONFLICT (word) DO NOTHING;");
            }
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Remove all seeded bad words
            migrationBuilder.Sql("DELETE FROM bad_words WHERE notes = 'Imported from bad-words-seed.txt';");
        }

        private static string[] GetBadWords()
        {
            return new[]
            {
                "2g1c", "2girls1cup", "4r5e", "5h1t", "5hit", "a_hole", "a_rse", "a55", "abbo", "abeed",
                "abuse", "accumulable", "accumulate", "accumulated", "accumulates", "accumulating", "accumulation",
                "accumulations", "accumulative", "accumulatively", "accumulativeness", "accumulator", "accumulators",
                "aclit", "acrotomophilia", "acumen", "acumens", "acuminata", "acuminate", "acuminated", "acuminating",
                "acumination", "adick", "aeolus", "africoon", "ahole", "aids", "alabamahotpocket", "alabamaporchmonkey",
                "alaskanpipeline", "alligatorbait", "allspices", "altocumulus", "amcik", "amputated", "amputates",
                "amputations", "amputator", "anal", "analannie", "analicker", "analintruder", "analinvader",
                "analprobe", "analsex", "andskota", "anilingus", "anus", "apeshit", "ar$ehole", "ar$hole",
                "ar$holes", "ar5e", "ar5h0le", "ar5h0les", "arabush", "arabushs", "areola", "areole", "argie",
                "armo", "armos", "aroused", "arrse", "ars3", "arschloch", "arse", "arse:arsenal", "arseh0le",
                "arseh0les", "arseho", "arsehol", "arsehole", "arseholes", "arsenals", "arsenate", "arsenical",
                "arsenicalism", "arsenics", "arsenide", "arsenides", "arsenious", "arsenite", "arsenites",
                "arsenium", "arseniuret", "arseniuretted", "arsenopyrite", "arsenotherapies", "arsenotherapy",
                "arsenous", "arsenoxide", "arsewipe", "arsh0le", "arshole", "arsholes", "aryan", "as$", "ash0le",
                "ash0les", "ashole", "asholes", "aspic", "ass", "assbag", "assbagger", "assbandit", "assbang",
                "assbanged", "assbanger", "assbangs", "assbite", "assblaster", "assclown", "asscock", "asscowboy",
                "asscrack", "asscracker", "assedout", "asses", "assface", "assfuck", "assfucker", "assfukka",
                "assgoblin", "assh0le", "assh0les", "assh0lez", "asshat", "asshead", "asshole", "assholes",
                "assholz", "asshopper", "asshore", "assjacker", "assjockey", "asskiss", "asskisser", "assklown",
                "asslick", "asslicker", "assload", "asslover", "assman", "assmaster", "assmonkey", "assmuch",
                "assmunch", "assmuncher", "assnigger", "assout", "asspacker", "asspirate", "asspuppies", "assrammer",
                "assranger", "assreamer", "assshit", "assshole", "asssucker", "asswad", "asswhacker", "asswhole",
                "asswhore", "asswipe", "asswipes", "asynclitism", "auspice", "auspices", "auspicial", "auspicious",
                "auspiciously", "auspiciousness", "autoerotic", "axwound", "ayir", "azazel", "azz", "azzhole",
                "b_ollocks", "b00b", "b00tha", "b00thas", "b0ll0cks", "b0llocks", "b17ch", "b1tch", "b3llend",
                "babcock", "babeland", "babes", "babybatter", "babyjuice", "backdoor", "backdoorman", "badfuck",
                "bagging", "ballbag", "ballbreaker", "ballbuster", "ballcock", "baller", "ballgag", "ballgravy",
                "balling", "ballkicking", "balllicker", "balllicking", "balls", "ballsack", "ballsucking",
                "bampot", "bangbro", "bangbros", "bangbus", "banger", "banging", "bareback", "barelylegal",
                "barenaked", "barf", "barface", "barfface", "bassterd", "bassterds", "bastard", "bastardo",
                "bastards", "bastardz", "basterd", "basterds", "basterdz", "bastinado", "basyard", "basyards",
                "batshit", "batty_nbsp;boi", "batty_nbsp;boy", "battyboy", "bawcock", "bawdy", "bazongas",
                "bazooms", "bbw", "bch", "bdsm", "beaner", "beaners", "beaney", "beaneys", "beardedclam",
                "beardedtaco", "beastality", "beastial", "beastiality", "beastility", "beatch", "beatoff",
                "beatyourmeat", "beaver", "beavercleaver", "beaverlips", "beavershot", "beeatch", "beefcurtains",
                "beener", "beeyotch", "belend", "bell_end", "bellend", "beotch", "bestial", "bestiality",
                "biatch", "bibcock", "bich", "bicurious", "bigass", "bigballer", "bigbastard", "bigblack",
                "bigbreasts", "bigbutt", "bigknockers", "bigtits", "billycock", "bimbo", "bimbos", "bin_dippers",
                "bindippers", "bint", "birdlock", "bitch", "bitchass", "bitched", "bitcher", "bitchers", "bitches",
                "bitchez", "bitchin", "bitching", "bitchslap", "bitchtit", "bitchtits", "bitchy", "biteme",
                "bitties", "blackcock", "blackman", "blackout", "blacks", "blewinski", "blondeaction",
                "blondeonblondeaction", "bloodclaat", "bloodfart", "bloody", "blow_job", "blowj", "blowjob",
                "blowjobs", "blowme", "blowmypole", "blowyourl", "blowyourload", "blueball", "blueballs",
                "bluegum", "bluegums", "bluewaffle", "blumpkin", "bo11ocks", "boabiesooking", "boabysooking",
                "boang", "boche", "boches", "bodily", "boffing", "bogan", "bohunk", "boink", "boiolas",
                "boll0cks", "bollick", "bollock", "bollocks", "bollok", "bollox", "bolocks", "bolox", "bombers",
                "bombing", "bomd", "bondage", "boned", "boner", "boner:deboner", "boners", "bong", "bonk:bonkers",
                "boob", "boobie", "boobs", "bookie", "boong", "boonga", "boongas", "boongs", "boonie", "boonies",
                "booobs", "boooobs", "booooobs", "booooooobs", "bootee", "bootha", "boothas", "bootlip",
                "bootlips", "bootycall", "boozer", "boozy", "bosch", "bosche", "bosches", "boschs", "bosomy",
                "bountybar", "breastjob", "breastlover", "breastman", "breasts", "brotherfucker", "brownshowers",
                "brunetteaction", "btch", "buceta", "buddhahead", "buddhaheads", "buffies", "bugger",
                "bugger:debugger", "buggered", "buggery", "bukake", "bukkake", "bullcrap", "bulldike", "bulldyke",
                "bulletvibe", "bullshit", "bullshits", "bullshitted", "bullturds", "bum", "bum_bandit", "bumbandit",
                "bumblefuck", "bumfuck", "bumh0l3", "bumh0le", "bumhol3", "bumhole", "bung", "bunga", "bungas",
                "bunghole", "burrhead", "burrheads", "busty", "butchbabes", "butchdike", "butchdyke", "butt",
                "butt_pirate", "buttbandit", "buttbang", "buttbanger", "buttbuddy", "buttcheeks", "buttcrack",
                "buttcrust", "buttface", "buttfuck", "buttfucka", "buttfucker", "buttfuckers", "butthead",
                "butthole", "butthump", "buttman", "buttmuch", "buttmunch", "buttmuncher", "buttnugger",
                "buttpirate", "buttplug", "buttporn", "buttstain", "buttwipe", "byatch", "c_nt", "c_u_n_t",
                "c_unt", "c00n", "c0ck", "c0cks", "c0cksucka", "c0cksucker", "c0k", "cabron", "caca", "cacker",
                "cacuminal", "caecum", "cahnt", "cahnts", "cahone", "cameljockey", "cameltoe", "camgirl",
                "camslut", "camwhore", "candy_ass", "canonicum", "capsicum", "capsicums", "caroticum",
                "carpeteater", "carpetmuncher", "carruth", "carse", "catharses", "cawk", "cawks", "cazzo", "cecum",
                "cervix", "charset", "chav", "cheesehead", "cheeseheads", "cherrypopper", "chesticle", "chickslick",
                "chinaman", "chinamen", "chinaswede", "chinaswedes", "chinc", "chincs", "chinga", "chingchong",
                "chingchongs", "chink", "chinks", "chinky", "choad", "chocolaterosebuds", "chode", "chodes",
                "chokemychicken", "chokingthechicken", "chonkies", "chonky", "chonkys", "choroidocyclitis",
                "chraa", "chuffnuts", "chug", "chugs", "chuj", "chunger", "chungers", "chunkies", "chunkys",
                "chute", "cialis", "cipa", "circlejerk", "circum", "circum_", "circumambience", "circumambient",
                "circumambulate", "circumambulated", "circumambulates", "circumambulating", "circumambulation",
                "circumambulations", "circumanal", "circumarticular", "circumbendibus", "circumcircle", "circumcise",
                "circumcised", "circumcises", "circumcising", "circumcision", "circumcisions", "circumcorneal",
                "circumduction", "circumductions", "circumference", "circumferences", "circumferential",
                "circumflex", "circumflexes", "circumfluent", "circumfluous", "circumforaneous", "circumfuse",
                "circumfusion", "circumgyration", "circuminsular", "circumjacence", "circumjacent", "circumlental",
                "circumlocution", "circumlocutions", "circumlocutory", "circumlunar", "circumnavigate",
                "circumnavigated", "circumnavigates", "circumnavigating", "circumnavigation", "circumnavigations",
                "circumnavigator", "circumnutate", "circumoral", "circumpolar", "circumrotation", "circumscissile",
                "circumscribe", "circumscribed", "circumscribes", "circumscribing", "circumscription",
                "circumscriptions", "circumsolar", "circumspect", "circumspection", "circumspectly",
                "circumspectness", "circumsphere", "circumstance", "circumstanced", "circumstances", "circumstantial",
                "circumstantiality", "circumstantially", "circumstantiate", "circumstantiated", "circumstantiates",
                "circumstantiating", "circumstantiation", "circumstantiations", "circumstantibus", "circumvallate",
                "circumvallation", "circumvascular", "circumvent", "circumventable", "circumvented", "circumventing",
                "circumvention", "circumventions", "circumvents", "circumvolution", "circumvolve", "cirrocumulus",
                "clamdigger", "clamdiver", "clamps", "clansman", "clansmen", "clanswoman", "clanswomen",
                "clevelandsteamer", "clit", "clit:anaclitic", "clitface", "clitfuck", "clitic", "clition",
                "clitoral", "clitoric", "clitoridean", "clitoridectomies", "clitoridectomy", "clitoridis",
                "clitoriditis", "clitoris", "clitorises", "clitoritis", "clitorus", "clits", "clitty", "clogwog",
                "cloverclamps", "clunge", "clusterfuck", "cnt", "cnts", "cntz", "cnut", "cnuts", "co(k", "coarse",
                "coarsely", "coarsen", "coarsened", "coarseness", "coarsening", "coarsens", "coarser", "coarsest",
                "coc_nbsp;k", "cocain", "cocaine", "cock", "cock:alcock", "cock_", "cock_a_doodle_doo",
                "cock_a_hoop", "cock_a_leekie", "cock_eyed", "cock_head", "cock_of_the_rock", "cock_sparrow",
                "cock_sucker", "cockade", "cockaded", "cockades", "cockaigne", "cockalorum", "cockamamie",
                "cockarouse", "cockass", "cockateel", "cockateels", "cockatiel", "cockatoo", "cockatoos",
                "cockatrice", "cockatrices", "cockayne", "cockbilled", "cockbite", "cockblock", "cockblocker",
                "cockboat", "cockburger", "cockchafer", "cockcowboy", "cockcroft", "cockcrow", "cockcrows",
                "cocked", "cocker", "cockerel", "cockerels", "cockers", "cockeye", "cockeyed", "cockeyes",
                "cockface", "cockfight", "cockfighting", "cockfights", "cockfucker", "cockhead", "cockholster",
                "cockhorse", "cockhorses", "cockier", "cockiest", "cockily", "cockiness", "cocking", "cockish",
                "cockjockey", "cockknob", "cockknocker", "cockknoke", "cockle", "cockleboat", "cocklebur",
                "cockled", "cockles", "cockleshell", "cockleshells", "cocklicker", "cockloft", "cocklord",
                "cocklover", "cockmaster", "cockmongler", "cockmongruel", "cockmonkey", "cockmunch", "cockmuncher",
                "cockness", "cockney", "cockneyfy", "cockneyism", "cockneys", "cocknob", "cocknocker", "cocknose",
                "cocknugget", "cockoldries", "cockpit", "cockpits", "cockqueen", "cockrider", "cockring",
                "cockroach", "cockroaches", "cocks", "cockscomb", "cockscombs", "cocksfoot", "cockshit", "cockshy",
                "cocksman", "cocksmith", "cocksmoke", "cocksmoker", "cocksniffer", "cockspur", "cockspurs",
                "cocksucer", "cocksuck", "cocksucka", "cocksucked", "cocksucker", "cocksuckers", "cocksuckers_",
                "cocksucking", "cocksucks", "cocksuka", "cocksukka", "cocksure", "cockswain", "cocktail",
                "cocktailed", "cocktails", "cocktease", "cockup", "cockups", "cockwaffle", "cocky", "cocoon",
                "cocooned", "cohee", "coital", "coitus", "cojones", "cok", "cokmuncher", "coksucka", "colchicum",
                "commie", "computability", "computable", "computation", "computational", "computations",
                "computative", "condom", "conspicuity", "conspicuous", "conspicuously", "conspicuousness",
                "coochie", "coochy", "coolie", "coolies", "cooly", "coon", "coon:barracoon", "coonass",
                "coonasses", "cooncan", "coondog", "coonhound", "coonhounds", "coons", "coonskin", "coonskins",
                "coontie", "cootch", "cooter", "cooze", "coprolagnia", "coprophilia", "copulate", "corksucker",
                "corncockle", "cornhole", "cossorali", "cox", "crabs", "crackbitch", "crackcocain", "cracker",
                "crackho", "crackpipe", "crackspacker", "crackspackler", "crackwhore", "crakker", "crap",
                "crap:crapaud", "crape", "craped", "crapface", "craphead", "crapola", "crapper", "crappers",
                "crappie", "crappieness", "crappier", "crappies", "crappiest", "crappiness", "crapping", "crappy",
                "craps", "crapshooter", "crapshooters", "crapulence", "crapulent", "crapulous", "creampie",
                "cretin", "cripple", "critest", "crotch", "crotchjockey", "crotchmonkey", "crotchrot", "cu_t",
                "cuck", "cucumber", "cucumbers", "cum", "cum:accumbent", "cumae", "cuman", "cumarin", "cumbelch",
                "cumbelcher", "cumbeltch", "cumbeltcher", "cumber", "cumbered", "cumberer", "cumberers",
                "cumbering", "cumberland", "cumberlandrian", "cumbernauld", "cumbers", "cumbersome",
                "cumbersomeness", "cumbrance", "cumbria", "cumbrous", "cumbrously", "cumbrousness", "cumbubble",
                "cumdumpster", "cumfest", "cumguzzle", "cumguzzler", "cumin", "cuming", "cumins", "cumjockey",
                "cumlapper", "cumlicker", "cumlickr", "cumm", "cummbubble", "cummdumpster", "cummer", "cummerbund",
                "cummerbunds", "cummers", "cummguzzler", "cummin", "cumming", "cummings", "cummins", "cummstain",
                "cummsucker", "cumquat", "cumquats", "cumqueen", "cums", "cumshaw", "cumshaws", "cumshot",
                "cumshots", "cumslut", "cumstain", "cumsucker", "cumsuker", "cumtart", "cumulate", "cumulated",
                "cumulates", "cumulating", "cumulation", "cumulative", "cumulatively", "cumulet", "cumuli",
                "cumuliform", "cumulonimbus", "cumulostratus", "cumulous", "cumulus", "cumwad", "cunilingus",
                "cunillingus", "cunn", "cunnie", "cunnilingus", "cunntt", "cunny", "cunt", "cuntass", "cunteyed",
                "cuntface", "cuntfuck", "cuntfucker", "cunthair", "cunthole", "cunthunter", "cunting", "cuntlick",
                "cuntlicker", "cuntlicking", "cuntrag", "cunts", "cunt's", "cuntslut", "cuntsucker", "cuntwhisker",
                "cuntwisker", "cuntz", "curcuma", "currymuncher", "currymunchers", "cushi", "cushis", "cushitic",
                "cutwater", "cuze", "cvnt", "cvnts", "cyalis", "cyberfuc", "cyberfuck", "cyberfucked", "cyberfucker",
                "cyberfuckers", "cyberfucking", "cybersex", "cyberslimer", "cyclitis", "cyclitol", "d__khead",
                "d_khead", "d1ck", "d1ck_", "d1ckh_ed", "d4mn", "dago", "dago:dagoba", "dagobas", "dagoes", "dagos",
                "dahmer", "daisychain", "daisygang", "damm", "dammit", "damn", "damnation", "damned", "damnit",
                "dangelberry", "dangleberry", "darkey", "darkeys", "darkie", "darkies", "darky", "daterape",
                "datnigga", "daygo", "deapthroat", "debuggers", "decumbence", "decumbency", "decumbent",
                "deepaction", "deepthroat", "deepthroating", "deeznuts", "defecate", "deggo", "dego", "degos",
                "demon", "dendrophilia", "deputation", "deputational", "deputations", "deputative", "derwentwater",
                "despicable", "despicably", "destroyyourpussy", "deth", "devil", "diaperdaddy", "diaperhead",
                "diaperheads", "dick", "dick_", "dick_nbsp;head", "dickbag", "dickbeater", "dickbeaters",
                "dickbrain", "dickbreath", "dickdipper", "dickface", "dickfiend", "dickflipper", "dickforbrains",
                "dickfuck", "dickfucker", "dickhead", "dickheads", "dickhole", "dickish", "dickjuice", "dickless",
                "dicklick", "dicklicker", "dickman", "dickmilk", "dickmonger", "dicknose", "dickpic", "dickripper",
                "dicks", "dicksipper", "dickslap", "dickslicker", "dicksucker", "dicksucking", "dicktickler",
                "dickwad", "dickweasel", "dickweed", "dickwhipper", "dickwod", "dickzipper", "diddle", "dikbreath",
                "dike", "dike_", "dikfiend", "dikhead", "dild0", "dild0s", "dildo", "dildos", "dilf", "diligaf",
                "dilld0", "dilld0s", "dillweed", "dimwit", "dingdong", "dingdonged", "dingelberry", "dingle",
                "dingleberries", "dingleberry", "dink", "dinks", "dipship", "dipshit", "dipstick", "dirsa",
                "dirtypillows", "dirtysanchez", "disencumber", "disencumbered", "disencumbering", "disencumbers",
                "disputability", "disputable", "disputably", "disputant", "disputants", "disputation", "disputations",
                "disputatious", "disputatiously", "disputatiousness", "disreputability", "disreputable",
                "disreputably", "dix", "dixiedike", "dixiedyke", "dlck", "document", "documentable", "documental",
                "documentaries", "documentarily", "documentary", "documentation", "documented", "documenter",
                "documenters", "documenting", "documents", "doggie", "doggiestyle", "doggin", "dogging",
                "doggystyle", "dogstyle", "dolcett", "domination", "dominatricks", "dominatrics", "dominatrix",
                "dommes", "dong", "dong:ding_dong", "dongola", "dongs", "donkeypunch", "donkeyribber", "doochbag",
                "doodoo", "doofus", "dookie", "doosh", "dork:dorking", "doronicum", "dothead", "dotheads",
                "doubledong", "doublepenetration", "douche", "douchebag", "douchebags", "douchewaffle", "douchey",
                "dpaction", "dragqueen", "dragqween", "drainthelizard", "dripdick", "drugs", "dryhump", "duche",
                "dudette", "dumass", "dumbass", "dumbasses", "dumbbitch", "dumbfuck", "dumbfucker", "dumbshit",
                "dumshit", "dunecoon", "dupa", "dvda", "dxxkhead", "dyefly", "dyke", "dykes", "dziwka",
                "earningredwings", "earotics", "easyslut", "eatadick", "eatballs", "eathairpie", "eatme",
                "eatmyass", "eatmyshorts", "eatpussy", "eboracum", "ecchi", "ecclesiasticum", "ecstacy", "ecumenic",
                "ecumenical", "ecumenicalism", "ecumenically", "ecumenicism", "ecumenicity", "ecumenism", "ecumenist",
                "eggplant", "ejackulate", "ejaculate", "ejaculated", "ejaculates", "ejaculating", "ejaculatings",
                "ejaculation", "ejakulate", "ekrem", "ekrem_", "ekto", "elasticum", "enclitic", "enclitically",
                "enculer", "encumber", "encumbered", "encumbering", "encumbers", "encumbrance", "encumbrancer",
                "encumbrances", "enema", "enlargement", "erect", "erection", "ero", "erotic", "erotism", "escort",
                "esqua", "esquimau", "essohbee", "ethicalslut", "ethnics", "eunuch", "evl", "excrement", "exkwew",
                "extacy", "extasy", "extispicious", "f$cks", "f()()k", "f()()ker", "f()()king", "f[_]cker",
                "f[_]cking", "f___", "f_____", "f______", "f_____g", "f____d", "f___ed", "f___in", "f___ing",
                "f__k", "f__k_ng", "f__ked", "f__ker", "f__kin", "f__kin'", "f__king", "f__ks", "f_c_", "f_ck",
                "f_cked", "f_cker", "f_ckin", "f_cking", "f_g", "f_gs", "f_ked", "f_ker", "f_ks", "f_nbsp;cked",
                "f_nbsp;u_nbsp;c_nbsp;k", "f_nbsp;uck", "f_nbsp;ucker", "f_nbsp;ucking", "f_o_a_d", "f_o_a_d_",
                "f_u_<_k", "f_u_c_k_", "f_uck", "f_uk", "f<uk", "f>>k", "f00k", "f00ked", "f0oked", "facefucker",
                "fack", "fackin", "facking", "faeces", "faen", "fag", "fag_", "fag1t", "fagbag", "faget",
                "fagfucker", "fagg", "fagg0t", "fagg1t", "fagged", "fagging", "faggit", "faggits", "faggitt",
                "faggot", "faggotcock", "faggs", "faghump", "fagit", "fagits", "fagmunch", "fagot", "fagots",
                "fags", "fagt", "fagtard", "fagz", "faig", "faigs", "faigt", "fanculo", "fanny", "fannybandit",
                "fannyflaps", "fannyfucker", "fanyy", "farsee", "farseeing", "farseing", "fart", "farted",
                "farting", "fartknocker", "farty", "fastfuck", "fatah", "fatass", "fatfuck", "fatfucker", "fatso",
                "fc_king", "fck", "f'ck", "fck_nbsp;ing", "fck1ng", "fckcum", "fckd", "fckeud", "fckin", "fcking",
                "fcks", "fckw1t", "fckwit", "fcuk", "fcuked", "fcuker", "fcukin", "fcuking", "fcuks", "feak",
                "fecal", "fecal:fecalith", "fecaloid", "feces", "feck", "fecker", "feckin", "fecking", "feg",
                "fekking", "felatio", "felch", "felched", "felcher", "felching", "fellate", "fellatio", "feltch",
                "feltcher", "feltching", "femalesquirtin", "femalesquirting", "femdom", "fetish", "ficken",
                "figging", "fingerbang", "fingerbanged", "fingerbanger", "fingerfood", "fingerfuck", "fingerfucked",
                "fingerfucker", "fingerfuckers", "fingerfucking", "fingerfucks", "fingering", "fisted", "fister",
                "fistfuck", "fistfucked", "fistfucker", "fistfuckers", "fistfucking", "fistfuckings", "fistfucks",
                "fisting", "fisty", "fitt", "fitt_", "fkin", "fking", "flamer", "flange", "flasher", "flikker",
                "flip", "flipping", "flippingthebird", "floggingthebishop", "flogthelog", "floo", "floozy",
                "flucknuts", "flydie", "flydye", "fo0ked", "foad", "foff", "fok", "fondle", "foobar", "fook",
                "fookd", "fooked", "fooker", "fookin", "fookin'", "fooking", "footaction", "footfetish", "footfuck",
                "footfucker", "footjob", "footlicker", "footstar", "foreskin", "forni", "fornicate", "fotze",
                "foursome", "fourtwenty", "fractocumulus", "freakfuck", "freakyfucker", "freefuck", "freex",
                "frig", "frigg", "frigga", "frigger", "frigging", "frigin", "friging", "frotting", "fu(_", "fu(k",
                "fu(ker", "fu(kers", "fu_ck", "fu_k", "fu_ker", "fu_kin", "fu_king", "fu_nbsp;ck", "fu_nbsp;cked",
                "fu_nbsp;cker", "fu_nbsp;cking", "fu<k", "fu<ked", "fu<ker", "fu<kin", "fu<king", "fu<kker",
                "fu<kr", "fu<ks", "fuc_nbsp;ked", "fuc_nbsp;ker", "fuc_nbsp;king", "fucck", "fuchah", "fuck",
                "fúck", "fúçk", "fùck", "fûck", "fück", "fuck_nbsp;ed", "fuck_nbsp;ing", "fuck_wit", "fucka",
                "fuckable", "fuckass", "fuckbag", "fuckbitch", "fuckbook", "fuckboy", "fuckbrain", "fuckbuddy",
                "fuckbutt", "fuckbutter", "fuckbuttons", "fuckd", "fucke_nbsp;d", "fucked", "fuckedup", "fucker",
                "fuckers", "fuckersucker", "fuckface", "fuckfest", "fuckfreak", "fuckfriend", "fuckhead",
                "fuckheads", "fuckher", "fuckhole", "fucki_nbsp;ng", "fuckin", "fuckina", "fucking", "fúcking",
                "fuckingbitch", "fuckinghell", "fuckings", "fuckingshitmotherfucker", "fuckinnuts", "fuckinright",
                "fuckit", "fuckk", "fuckknob", "fuckme", "fuckmeat", "fuckmehard", "fuckmonkey", "fuckn",
                "fucknugget", "fucknut", "fucknuts", "fucknutt", "fucknutz", "fuckoff", "fuckpig", "fuckpuppet",
                "fuckr", "fucks", "fuckshit", "fuckstick", "fucktard", "fucktards", "fucktart", "fucktoy",
                "fucktrophy", "fuckup", "fuckw1t", "fuckwad", "fuckwhit", "fuckwhore", "fuckwit", "fuckwits",
                "fuckwitt", "fuckyomama", "fuckyou", "fucw1t", "fucwit", "fudge_p_cker", "fudge_packer",
                "fudgep_cker", "fudgepacker", "fudgpacker", "fugly", "fuk", "fuk_", "fukah", "fukced", "fuked",
                "fuken", "fuker", "fukin", "fuking", "fukk", "fukka", "fukkah", "fukked", "fukken", "fukker",
                "fukkhead", "fukkin", "fukking", "fuks", "fuktard", "fuktards", "fukwhit", "fukwit", "fukyou",
                "funfuck", "fungus", "furbox", "furbuger", "furburger", "furryburger", "furyburger", "futanari",
                "futanary", "futkretzn", "fuuck", "fuukn", "fux", "fux0r", "fuxor", "fvck", "fvck_up", "fvcker",
                "fvckface", "fvcking", "fvcknut", "fvcknuts", "fvckup", "fvckw1t", "fvckwit", "fvckyou", "fvk",
                "fxck", "g_spot", "g00k", "gae", "gai", "gamecock", "gamecocking", "gamecocks", "gang_bang",
                "gangbang", "gangbanged", "gangbanger", "gangbangs", "gangsta", "ganja", "gash", "gassyass",
                "gatorbait", "gay", "gayass", "gaybob", "gaybor", "gayboy", "gaydo", "gayfuck", "gayfuckist",
                "gaygirl", "gayhole", "gaylord", "gaymuthafuckinwhore", "gays", "gaysex", "gaytard", "gaywad",
                "gayz", "geezer", "geni", "genital", "genitals", "genocide", "getiton", "gey", "gfy", "ghay",
                "ghey", "giantcock", "gigolo", "gimp", "ginch", "ginzo", "ginzos", "gipp", "gippo", "gippos",
                "gipps", "girlie_gardening", "girlon", "girlontop", "girlsgonewild", "givehead", "glans",
                "glaucomatocyclitic", "glazeddonut", "gniga", "gnikcuf", "goatcx", "goatse", "gob", "god_damned",
                "godam", "godammit", "godamn", "godamnit", "goddam", "goddamit", "goddamm", "goddammit", "goddamn",
                "goddamned", "goddamnes", "goddamnit", "goddamnmuthafucker", "godsdamn", "gokkun", "goldenshower",
                "golliwog", "golliwogs", "gonad", "gonads", "gonorrehea", "gonzagas", "gooch", "goodpoop",
                "googirl", "gook", "gookeye", "gookeyes", "gookies", "gooks", "gooky", "gora", "goras", "gorcock",
                "goregasm", "goris", "gotohell", "goy", "goyim", "greaseball", "greaseballs", "gringo", "groe",
                "groid", "groids", "grope", "grostulation", "groupsex", "gspot", "gstring", "gtfo", "guaiacum",
                "gub", "gubba", "gubbas", "gubs", "guido", "guiena", "guineas", "guizi", "gummer", "guro",
                "gwailo", "gwailos", "gweilo", "gweilos", "gyopo", "gyopos", "gyp", "gyped", "gypo", "gypos",
                "gypp", "gypped", "gyppie", "gyppies", "gyppo", "gyppos", "gyppy", "gyppys", "gypsys", "h00r",
                "h0ar", "h0m0", "h0mo", "h0r", "h0re", "h4x0r", "hadji", "hadjis", "hairyback", "hairybacks",
                "hairyhatchetwound", "hairytaco", "haji", "hajis", "hajji", "hajjis", "half_cock", "half_cocked",
                "halfbreed", "halfcaste", "hamas", "hamflap", "hancock", "handjob", "haole", "haoles", "hapa",
                "hardcore", "hardcoresex", "hardon", "harem", "haruspical", "haycock", "haycocks", "headfuck",
                "hearse", "hearsed", "hearses", "hebe", "hebes", "heeb", "heebs", "hell", "hells", "helvete",
                "hentai", "heraclitus", "hermaphrodite", "heroin", "herp", "herpes", "herpy", "heshe", "heteroclite",
                "hijacker", "hijacking", "hillbillies", "hillbilly", "hindoo", "hiscock", "hitchcock", "hitler",
                "hitlerism", "hitlerist", "ho", "hoar", "hoare", "hoarse", "hoarsely", "hoarsen", "hoarsened",
                "hoarseness", "hoarsening", "hoarsens", "hoarser", "hoarsest", "hobag", "hodgie", "hoe", "hoer",
                "hoer_", "hoes", "holestuffer", "homey", "hommo", "homo", "homobangers", "homodumbshit",
                "homoerotic", "homoey", "honger", "honkers", "honkey", "honkeys", "honkie", "honkies", "honky",
                "hooch", "hoochiemama", "hooker", "hookers", "hoor", "hoore", "hootch", "hooter", "hooters",
                "hore", "hori", "horis", "hork", "horndawg", "horndog", "horney", "horniest", "horny", "horseshit",
                "hosejob", "hoser", "hospice", "hospices", "hotbeefinjection", "hotcarl", "hotchick", "hotdamn",
                "hotpussy", "hotsex", "hottotrot", "howtokill", "howtomurdep", "howtomurder", "huev", "huevon",
                "hugefat", "hui", "humbugger", "hummer", "humped", "humper", "humpher", "humphim", "humpin",
                "humping", "hussy", "hustler", "hvns", "hymen", "hymie", "hymies", "hypericum", "iblowu", "ike",
                "ikes", "ikey", "ikeymo", "ikeymos", "ikwe", "ileocecum", "illegal", "illegals", "illyricum",
                "imperspicuity", "imputable", "imputation", "imputations", "imputative", "inauspicious",
                "inauspiciously", "inauspiciousness", "inbred", "incest", "incomputable", "incomputably",
                "inconspicuous", "inconspicuously", "inconspicuousness", "incumbencies", "incumbency", "incumbent",
                "incumbently", "incumbents", "incumber", "incumbered", "incumbering", "incumbers", "incumbrance",
                "incumbrancer", "indisputable", "indisputableness", "indisputably", "indon", "indons", "injun",
                "injuns", "insest", "inspissated", "intercourse", "interracial", "intheass", "inthebuff",
                "iridocyclitis", "israelians", "israels", "ities", "jackass", "jackhole", "jackingoff", "jackoff",
                "jackshit", "jacktheripper", "jagoff", "jailbait", "jap", "japcrap", "japie", "japies", "japs",
                "jebus", "jellydonut", "jerk", "jerk_off", "jerkass", "jerked", "jerkingoff", "jerkoff", "jerries",
                "jerry", "jewboy", "jewed", "jewess", "jiga", "jigaboo", "jigaboos", "jigarooni", "jigaroonis",
                "jigg", "jigga", "jiggabo", "jiggaboo", "jiggabos", "jiggas", "jigger", "jiggerboo", "jiggers",
                "jiggs", "jiggy", "jigs", "jihad", "jijjiboo", "jijjiboos", "jimfish", "jisim", "jism", "jiss",
                "jiz", "jizer", "jizim", "jizin", "jizjuice", "jizm", "jizmuffin", "jizn", "jizsandwich", "jizz",
                "jizzd", "jizzed", "jizzer", "jizzim", "jizzin", "jizzm", "jizzmuffin", "jizzn", "jizzsandwich",
                "jizzum", "jugg", "juggs", "jugs", "junglebunny", "junkie", "junky", "k__t", "k_ffir", "k_ffirs",
                "k_fir", "k_firs", "kacap", "kacapas", "kacaps", "kaf1r", "kaff1r", "kaffer", "kaffir", "kaffirs",
                "kaffre", "kafir", "kafirs", "kafr", "kanake", "kanker", "kanker_", "kants", "katharses", "katsap",
                "katsaps", "kawk", "kcid", "kcuf", "khokhol", "khokhols", "khunt", "kicking", "kiddie_fiddler",
                "kiddie_fiddling", "kiddiefiddler", "kiddiefiddling", "kiddy_fiddler", "kiddyfiddler", "kigger",
                "kike", "kikes", "kill", "kimchis", "kinbaku", "kink", "kinkster", "kinky", "kinkyjesus", "kissass",
                "kiunt", "kkk", "klan", "klansman", "klansmen", "klanswoman", "klanswomen", "klootzak", "kn0b",
                "knob", "knob_nbsp;head", "knobber", "knobbing", "knobead", "knobed", "knobend", "knobhead",
                "knobjocky", "knobjokey", "knobs", "knobz", "knockers", "knulle", "kock", "kondum", "kondums",
                "kooch", "kooches", "koochie", "koochy", "koon", "kootch", "kootchie", "kootchy", "krap", "krappy",
                "kraut", "krauts", "kuffar", "kuk", "kuksuger", "kum", "kumbubble", "kumbullbe", "kumer", "kumm",
                "kummer", "kumming", "kumquat", "kums", "kunilingus", "kunnilingus", "kunt", "kunts", "kuntz",
                "kurac", "kurwa", "kushi", "kushis", "kusi", "kusi_", "kwa", "kwif", "kyke", "kykes", "kyopo",
                "kyopos", "kyrpa", "kyrpa_", "l_m_f_a_o", "l_m_f_a_o_", "l3i+ch", "l3itch", "labia", "lactoids",
                "lameass", "laocoon", "lapdance", "laputa", "laputan", "lardass", "larsen", "leacock",
                "leatherrestraint", "leatherstraightjacket", "lebos", "lech", "lemonparty", "leper", "lesbain",
                "lesbayn", "lesbian", "lesbin", "lesbo", "lesbo:blesbok", "lesbos", "lesbyterian", "lettucepicker",
                "lez", "lezbe", "lezbefriends", "lezbian", "lezbians", "lezbo", "lezbos", "lezz", "lezzian",
                "lezzie", "lezzies", "lezzo", "lezzy", "libido", "lickcock", "licker", "licking", "lickme",
                "lickmynuts", "licknipple", "lilniglet", "limey", "limpdick", "limy", "lingerie", "lipshits",
                "lipshitz", "livesex", "lmfa0", "lmfao", "loadedgun", "locum", "locumtenencies", "locumtenency",
                "loin", "loins", "lolita", "lovebone", "lovecanal", "lovegoo", "lovegun", "lovejuice", "lovemaking",
                "lovemuscle", "lovepistol", "loverocket", "lowlife", "lsd", "lubejob", "lubra", "lucifer",
                "luckycammeltoe", "lugan", "lugans", "lust", "lusting", "lusty", "lynch", "m_inge",
                "m_otherf_ucker", "m1nge", "mabuno", "mabunos", "macaca", "macacas", "macumba", "mafugly",
                "magicwand", "mahbuno", "mahbunos", "makemecome", "makemecum", "malesquirting", "mamhoon", "mams",
                "man_root", "mangina", "manhater", "manpaste", "manwhore", "maricon", "maricón", "marijuana",
                "marse", "marseillaise", "marseille", "marseilles", "marses", "masochist", "masokist", "massa",
                "massterbait", "masstrbait", "masstrbate", "massturbate", "mastabate", "mastabater", "masterbaiter",
                "masterbat", "masterbat_", "masterbat3", "masterbate", "masterbates", "masterbating", "masterbation",
                "masterbations", "masterblaster", "mastrabator", "masturbat", "masturbat_", "masturbate",
                "masturbating", "masturbation", "mattressprincess", "maumau", "maumaus", "mcfagget", "meatbeatter",
                "meatrack", "mecum", "mecums", "menage", "menageatrois", "merd", "merd_", "mesocecum", "mgger",
                "mggor", "mibun", "mick", "mickeyfinn", "middlesboro", "mideast", "mierda", "milf", "minge",
                "minger", "miscomputation", "mispickel", "missionaryposition", "mockey", "mockie", "mocky",
                "modicum", "modicums", "mof__ker", "mof__kers", "mofo", "mofuccer", "mofucker", "mofuckers",
                "mofucking", "mofukcer", "mohterf__ker", "mohterf__kers", "mohterf_kcer", "mohterfuccer",
                "mohterfuccers", "mohterfuck", "mohterfucker", "mohterfuckers", "mohterfucking", "mohterfucks",
                "mohterfuk", "mohterfukcer", "mohterfukcers", "mohterfuking", "mohterfuks", "moky", "molest",
                "molestation", "molester", "molestor", "molluscum", "moneyshot", "mong", "monkeydick", "monkeyhumper",
                "monkleigh", "mooli", "moolie", "mooncricket", "mooncrickets", "moorcock", "mormon", "moron",
                "moskal", "moskals", "moslem", "mosshead", "moterf__ker", "moterfuccer", "moterfuck", "moterfucker",
                "moterfuckers", "moterfucking", "moterfucks", "motha", "motha_fucka", "mothaf__k", "mothaf__ker",
                "mothaf__kers", "mothaf__king", "mothaf__ks", "mothafuccer", "mothafuck", "mothafucka", "mothafuckas",
                "mothafuckaz", "mothafucked", "mothafucker", "mothafuckers", "mothafuckin", "mothafuckin'",
                "mothafucking", "mothafuckings", "mothafucks", "mothafuker", "mothafukkah", "mothafukker",
                "mother_fucker", "motherf___ers", "motherf__ked", "motherf__ker", "motherf__kers", "motherfuccer",
                "motherfuccers", "motherfuck", "motherfucka", "motherfucked", "motherfucker", "motherfuckers",
                "motherfuckin", "motherfucking", "motherfuckings", "motherfuckka", "motherfucks", "motherfukah",
                "motherfuker", "motherfukkah", "motherfukker", "motherfukkker", "motherfvcker", "motherlovebone",
                "mothrfucker", "mouliewop", "moundofvenus", "mrhands", "mthaf__ka", "mthafucca", "mthafuccas",
                "mthafucka", "mthafuckas", "mthafukca", "mthafukcas", "mtherfucker", "mthrfuck", "mthrfucker",
                "mthrfucking", "mtrfck", "mtrfuck", "mtrfucker", "mudpeople", "mudperson", "muff", "muff_diver",
                "muff_diving", "muffdive", "muffdiver", "muffdiving", "muffindiver", "mufflikcer", "muffpuff",
                "muffs", "muie", "mulatto", "muli", "mulkku", "muncher", "mung", "munging", "munt", "munter",
                "murder", "muschi", "muth_fucker", "mutha", "muthaf__k", "muthaf__ker", "muthaf__kers",
                "muthaf__king", "muthaf__ks", "muthafecker", "muthafuccer", "muthafuck", "muthafuck_", "muthafucka",
                "muthafuckaz", "muthafucker", "muthafuckers", "muthafucking", "muthafuckker", "muthafucks",
                "muthafukah", "muthafukas", "muthafuker", "muthafukkah", "muthafukker", "muther", "mutherfucker",
                "mutherfucking", "muthrfucking", "mzungu", "mzungus", "n1gr", "nad", "nads", "naked", "nambla",
                "nappy", "nastt", "nasty", "nastybitch", "nastyho", "nastyslut", "nastywhore", "nawashi", "nazi",
                "nazis", "nazism", "necked", "necro", "needthedick", "negres", "negress", "negro", "negroes",
                "negroid", "negros", "neonazi", "nepesaurio", "nestlecock", "nig", "nig_nog", "niga", "nigaboo",
                "nigar", "nigars", "nigas", "niger", "nigers", "nigette", "nigettes", "nigg", "nigga", "niggah",
                "niggahs", "niggar", "niggaracci", "niggard", "niggarded", "niggarding", "niggardliness",
                "niggardlinesss", "niggardly", "niggards", "niggars", "niggas", "niggaz", "nigger", "nigger:snigger",
                "nigger;", "nigger_", "niggerhead", "niggerhole", "niggers", "niggle", "niggled", "niggles",
                "niggling", "nigglings", "niggor", "niggress", "niggresses", "nigguh", "nigguhs", "niggur",
                "niggurs", "niglet", "nignog", "nigor", "nigors", "nigr", "nigra", "nigras", "nigre", "nigres",
                "nigress", "nigs", "nigur", "nigur;", "niiger", "niiger;", "niigr", "niigr;", "nimphomania",
                "nimrod", "ninny", "nip", "nipissing", "nipple", "nipplering", "nipples", "nips", "nittit",
                "nlgger", "nlggor", "nob", "nob_nbsp;head", "nobhead", "nobjocky", "nobjokey", "nocumetum",
                "nofuckingway", "nog", "nonce", "noncumulative", "nonimputability", "nonimputable", "nookey",
                "nookie", "nooky", "noonan", "nooner", "noricum", "nsfw", "nsfwimages", "nude", "nudger", "nudie",
                "nudies", "nudity", "numbnuts", "nutbutter", "nutfucker", "nutsack", "nutted", "nutten", "nutter",
                "nutting", "nymph", "nympho", "nympho:nympholepsies", "nympholepsy", "nymphomania", "nymphomaniac",
                "nymphomaniacal", "nymphomaniacs", "octopussy", "oecumenical", "omorashi", "onanism", "onecuptwogirls",
                "oneguyonejar", "onewaypipecleaner", "ontherag", "orafis", "orally", "orga", "orgasim", "orgasim;",
                "orgasims", "orgasm", "orgasmic", "orgasms", "orgasum", "orgies", "orgy", "oriface", "orifice",
                "orifiss", "orospu", "osama", "oversuspicious", "ovum", "ovums", "p__i", "p_iss_flaps", "p_ki",
                "p_kis", "p00f", "p00fs", "p00fter", "p00fters", "p0of", "p0rn", "packi", "packie", "packy",
                "paddy", "paedo", "paedophile", "paedophiles", "pak1", "paki", "pakie", "pakis", "paky",
                "palesimian", "panocha", "panooch", "pansies", "pansy", "panti", "pantie", "panties", "panty",
                "parse", "parsec", "parsecs", "parsed", "parsee", "parser", "parsers", "parses", "paska", "paska_",
                "pastie", "pasty", "pawn", "payo", "pcp", "peacock", "peacocked", "peacockier", "peacocking",
                "peacocks", "peado", "peadofile", "peadofiles", "pearlnecklace", "pecker", "peckerhead",
                "peckernose", "peckerwood", "pedagogic", "pedagogical", "pedagogically", "pedagogics", "pedagogs",
                "pedagogue", "pedagogues", "pedagogy", "pedo", "pedobear", "pedophile", "pedophilia", "pedophiliac",
                "pee", "peedo", "peedofile", "peedofiles", "peedophile", "peedophiles", "peedos", "peeenus",
                "peeenusss", "peehole", "peenus", "peepee", "peepshow", "peepshpw", "pegging", "peinus", "pen1s",
                "penas", "pench0d", "pench0ds", "penchod", "penchods", "pendejo", "pendy", "penetrate", "penetration",
                "penial", "penile", "penis", "penis_breath", "penisbanger", "penisbreath", "penises", "penisfucker",
                "penisland", "penislick", "penislicker", "penispuffer", "penthouse", "penus", "penuus", "perdol",
                "perse", "perspicacious", "perspicaciously", "perspicaciousness", "perspicacity", "perspicuity",
                "perspicuous", "perspicuously", "perspicuousness", "perv", "perversion", "peshitta", "petcock",
                "petcocks", "peyote", "phalli", "phallic", "phanny", "phanny_", "pheck", "phecking", "phelch",
                "phelcher", "phelching", "pheltch", "pheltcher", "pheque", "phequing", "phlip", "phonesex", "phuc",
                "phuck", "phucker", "phuckin", "phucking", "phucks", "phuk", "phuked", "phuker", "phuking",
                "phukked", "phukker", "phukking", "phuks", "phungky", "phuq", "picaninny", "piccaninny", "picka",
                "pickaninnies", "pickaninny", "pieceofshit", "piefke", "piefkes", "pierdol", "pierdol_", "pigfucker",
                "piker", "pikey", "piky", "pillow_biter", "pillowbiter", "pillu", "pillu_", "pimmel", "pimp",
                "pimped", "pimper", "pimpis", "pimpjuic", "pimpjuice", "pimpsimp", "pinchcock", "pindick",
                "piniswrinkle", "pinko", "pinpricked", "pipehitter", "pis", "pises", "pisin", "pising", "pisof",
                "piss", "piss:inspissate", "piss_", "pissant", "pissants", "pissarro", "pissdrinker", "pissed",
                "pisser", "pissers", "pisses", "pissflap", "pissflaps", "pisshead", "pissin", "pissing", "pisslicker",
                "pissoff", "pisspig", "pistol", "pito", "pizda", "playboy", "playgirl", "pleasurechest", "po0f",
                "pocha", "pochas", "pocho", "pochos", "pocketpool", "poff", "pohm", "pohms", "polac", "polack",
                "polacks", "polak", "polesitter", "polesmoker", "polishingthetorpedo", "polishthebishop", "polliwog",
                "polliwogs", "pollock", "pollocks", "pollywog", "pollywogs", "polock", "polyclitus", "pommy",
                "ponce", "ponyplay", "poo", "poof", "poofs", "poofter", "poon", "poonani", "poonany", "poontang",
                "poontsee", "poop", "poopchute", "pooper", "pooperscooper", "pooping", "poopstain", "poorwhitetrash",
                "poostabber", "poostabbers", "popimp", "poppedcherry", "poppycock", "porchmonkey", "porn", "pornflick",
                "pornking", "porno", "pornography", "pornos", "pornprincess", "poundtown", "pplicker", "pr_ck",
                "pr_ck_", "pr0n", "pr1c", "pr1ck", "pr1ck_", "pr1cks", "pr1cks_", "pr1k", "premature", "preteen",
                "pric", "prick", "prick:pinprick", "prickhead", "prickier", "prickiest", "pricking", "prickle",
                "prickles", "pricklier", "prickliest", "prickliness", "prickling", "prickly", "pricks", "pricky",
                "prig", "prik", "primadonnas", "primming", "princealbertpiercing", "proclitic", "procumbent",
                "pron", "prostitute", "psilocybin", "psychocatharses", "pthc", "pu$$y", "pu55y", "pube", "pubes",
                "pubic", "pubiclice", "pubis", "publicum", "puccoon", "pud", "pudboy", "pudd", "puddboy", "puke",
                "pula", "pule", "punani", "punanny", "punany", "punkass", "punky", "punta", "puntang",
                "purinapricness", "pusies", "puss", "pusse", "pussee", "pussi", "pussie", "pussies", "pussy",
                "pussy:pussycat", "pussycat", "pussycats", "pussydestroyer", "pussyeater", "pussyfart", "pussyfoots",
                "pussyfucker", "pussyjuice", "pussyjuiced", "pussyjuicer", "pussyjuicing", "pussylicker",
                "pussylicking", "pussylips", "pussylover", "pussypalace", "pussypounder", "pussypounding", "pussys",
                "pussywhipped", "pussywhipper", "pussywiped", "pusy", "puta", "puta:amputate", "putamen", "putamina",
                "putative", "putatively", "puto", "puuke", "puuker", "pv55ie", "pv55y", "pyogenicum", "qahbeh",
                "quandong", "quashie", "queaf", "queef", "queef_", "queer", "queerbait", "queerhole", "queero",
                "queers", "queerz", "queve", "quickie", "quicky", "quiff", "quim", "quim:equimolecular", "quimper",
                "quimsteak", "qveer", "qweers", "qweerz", "qweir", "raccoon", "raccoons", "racoon", "racoons",
                "raghead", "ragheads", "ragingboner", "rajputana", "rape", "raped", "raper", "raping", "rapist",
                "rautenberg", "reamputation", "rearend", "rearentry", "recktum", "rectal", "rectum", "rectus",
                "recumbencies", "recumbency", "recumbent", "redleg", "redlegs", "redlight", "redneck", "rednecks",
                "redskin", "redskins", "reefer", "reestie", "reetard", "rehearse", "rehearsed", "rehearser",
                "rehearsers", "rehearses", "reich", "renob", "rentafuck", "reputability", "reputable",
                "reputableness", "reputably", "reputation", "reputations", "rere", "ret_rd", "retard", "retarded",
                "retards", "retardz", "reversecowgirl", "rigger", "rimadonna:primadonna", "rimjaw", "rimjob",
                "rimming", "rimming:brimming", "ritard", "rootle:rootless", "rootlessness", "rosebuds", "rosypalm",
                "rosypalmandher5sisters", "rosypalmandherefivesisters", "roundeye", "rtard", "rtards", "rugmunch",
                "rugmunched", "rugmuncher", "rumprammer", "rumpranger", "rumpshaker", "ruski", "russki", "russkie",
                "rusticum", "rustytrombone", "s_hit", "s_m", "s_o_b", "s1ut", "sac", "sachamo", "sadis", "sadism",
                "sadist", "sadom", "saltwater", "sambo", "sambos", "samckdaddy", "sanchez", "sandm", "sandniggah",
                "sandnigger", "santorum", "sappho", "sarsen", "sarsenet", "sarsent", "satanic", "saturdayish",
                "sausagequeen", "scag", "scallywag", "scank", "scantily", "scat", "schaffer", "scheiss", "scheiss_",
                "schizo", "schlampe", "schlong", "schmuck", "schvartse", "schvartsen", "schwartze", "schwartzen",
                "scissoring", "scrap", "scrapbook", "scrapbooks", "scrape", "scraped", "scraper", "scraperboard",
                "scrapers", "scrapes", "scrapheap", "scrapie", "scraping", "scrapings", "scrappage", "scrapped",
                "scrapper", "scrappers", "scrappier", "scrappiest", "scrappily", "scrappiness", "scrapping",
                "scrapple", "scrapples", "scrappy", "scraps", "screw", "screwed", "screwing", "screwyou", "scroat",
                "scrog", "scrote", "scrotum", "scrubbingthecarrot", "scrud", "scum", "scum_", "scumbag", "scumber",
                "scumble", "scumbled", "scumbling", "scummed", "scummers", "scummier", "scummiest", "scumming",
                "scummy", "scums", "scunthorpe", "seacock", "seduce", "semen", "seppo", "seppos", "septics", "sex",
                "sexcam", "sexed", "sexfarm", "sexhound", "sexhouse", "sexi", "sexing", "sexkitten", "sexo",
                "sexpot", "sexslave", "sextogo", "sextoy", "sextoys", "sexual", "sexuality", "sexually", "sexwhore",
                "sexx", "sexxi", "sexxx", "sexxxi", "sexxxy", "sexxy", "sexy", "sexymoma", "sexyslim", "sh_t",
                "sh_t", "sh_te", "sh_tes", "sh1t", "sh1te", "sh1ter", "sh1ts", "sh1tter", "sh1tz", "shag",
                "shag:shagbark", "shagbarks", "shagbucket", "shagger", "shaggin", "shagging", "shagstress",
                "shamedame", "sharmuta", "sharmute", "shat", "shav", "shavedbeaver", "shavedpussy", "shawtypimp",
                "sheeney", "shemale", "shhit", "shibari", "shibary", "shinola", "shipal", "shirtlifter",
                "shirtlifters", "shit", "shiit", "shiiit", "sh1t", "shit:brushite", "shitass", "shitbag",
                "shitbagger", "shitblimp", "shitbrain", "shitbrains", "shitbreath", "shitcan", "shitcanned",
                "shitcunt", "shitdick", "shite", "shiteater", "shiteating", "shited", "shitey", "shitface",
                "shitfaced", "shitfit", "shitforbrains", "shitfuck", "shitfucker", "shitfull", "shithapens",
                "shithappens", "shithead", "shitheel", "shithole", "shithouse", "shiting", "shitings", "shitkicker",
                "shitlist", "shitload", "shitola", "shitoutofluck", "shitpot", "shitpusher", "shits", "shitshover",
                "shitspitter", "shitstabber", "shitstabbers", "shitstain", "shitt", "shitted", "shitter", "shitters",
                "shittiest", "shitting", "shittings", "shitty", "shity", "shitz", "shiz", "shiznit", "shortfuck",
                "shota", "shrimping", "shuttlecock", "shuttlecocks", "shylock", "shylocks", "shyt", "shyte",
                "shytty", "shyty", "simp", "sissy", "sixsixsix", "sixtynine", "sixtyniner", "skag", "skanck",
                "skank", "skankbitch", "skankee", "skankey", "skankfuck", "skanks", "skankwhore", "skanky",
                "skankybitch", "skankywhore", "skeet", "skinflute", "skrib", "skribz", "skullfuck", "skullfucked",
                "skullfucker", "skullfucks", "skum", "skumbag", "skurwysyn", "skwa", "skwe", "skyscrape", "skyscraper",
                "skyscrapers", "skyscraping", "slag", "slanteye", "slanty", "slapingthesausage", "slapper",
                "slapthesalami", "sleezeball", "slideitin", "slimeball", "slimebucket", "slitlicker", "slocum",
                "slope", "slopehead", "slopeheads", "sloper", "slopers", "slopes", "slopey", "slopeys", "slopies",
                "slopy", "slut", "slutbag", "slutbucket", "slutdumper", "slutkiss", "sluts", "slutt", "slutting",
                "slutty", "slutwear", "slutwhore", "slutz", "smack", "smackthemonkey", "smeg", "smegma", "smoker",
                "smut", "smutty", "snarf", "snatch", "snatchpatch", "snigger", "sniggered", "sniggering", "sniggers",
                "snog", "snowback", "snowballing", "snownigger", "snuff", "socksucker", "sodom", "sodomise",
                "sodomised", "sodomiser", "sodomite", "sodomize", "sodomized", "sodomizer", "sodomy", "solidago",
                "solidagos", "son_of_a_bitch", "sonofabitch", "sonofbitch", "sooties", "sooty", "souse", "soused",
                "soyboy", "spac", "spade", "spades", "spaghettibender", "spaghettinigger", "spank", "spankthemonkey",
                "sparse", "sparsely", "sparseness", "sparser", "sparsest", "spastic", "spatchcock", "spatchcocked",
                "spatchcocking", "spaz", "spearchucker", "spearchuckers", "sperm", "spermacide", "spermbag",
                "spermhearder", "spermherder", "sphencter", "sphincterboy", "sphincterface", "spic", "spic:allspice",
                "spica", "spicaes", "spicas", "spicate", "spiccato", "spice", "spiceberry", "spicebush", "spiced",
                "spicer", "spicers", "spicery", "spices", "spicey", "spicier", "spiciest", "spicily", "spiciness",
                "spicing", "spick", "spick_and_span", "spicks", "spics", "spicula", "spicular", "spiculate",
                "spiculated", "spiculation", "spicule", "spicules", "spiculum", "spicy", "spierdalaj", "spig",
                "spigotty", "spik", "spiks", "spit_roast", "spit_roasting", "spitchcock", "spitroast", "spitroasting",
                "spitter", "splittail", "splooge", "sploogemoose", "spludge", "spooge", "spook", "spreadeagle",
                "spreadlegs", "spunk", "spunking", "spunkmonkey", "spunky", "sputa", "sqeh", "squa", "squarehead",
                "squareheads", "squaw", "squinty", "squirting", "ß0ll0çk5", "stagg", "steamy", "stfu", "stiffy",
                "stoned", "stoner", "stopcock", "stopcocks", "storm_cock", "strapon", "strappado", "stratocumuli",
                "stratocumulus", "stringer", "stripclub", "stroke", "stroking", "strollop", "stuinties", "stupidfuck",
                "stupidfucker", "sturdiest", "sturdily", "sturdiness", "sturdy", "styledoggy", "succumb", "succumbed",
                "succumber", "succumbers", "succumbing", "succumbs", "suck", "suckass", "suckdick", "sucked",
                "sucker", "sucking", "suckme", "suckmyass", "suckmydick", "suckmytit", "suckoff", "sucks",
                "suckster", "suicide", "suicidegirl", "suicidegirls", "suka", "sultrywoman", "sultrywomen",
                "sumofabiatch", "superincumbent", "supputation", "suspicion", "suspicions", "suspicious",
                "suspiciously", "suspiciousness", "swallower", "swalow", "swanked", "swankier", "swankiest",
                "swankily", "swanking", "swastika", "swinger", "sx", "synclitic", "syphilis", "t_w_a_t", "t_wat",
                "t0$$er", "t0sser", "t0ssers", "taboo", "tacohead", "tacoheads", "taff", "taint", "taintedlove",
                "talcum", "talcums", "taraxacum", "tarbaby", "tard", "tarsectomies", "tarsectomy", "tastemy",
                "tawdry", "tea_bagging", "teabagging", "teat", "tecum", "tecumseh", "teets", "teez", "terd",
                "terror", "terrorist", "teste", "testee", "testes", "testical", "testicle", "testicles",
                "testicular", "testis", "thicklip", "thicklips", "thirdeye", "thirdleg", "threesome", "threeway",
                "throating", "thumbzilla", "thundercunt", "tiedup", "tightwhite", "tillicum", "timbernigger",
                "tinkle", "tippolisher", "tit", "titbitnipply", "titfuck", "titfucker", "titfuckin", "titi",
                "titjob", "titlicker", "titlover", "tits", "titt", "titt_", "tittie", "tittiefucker", "titties",
                "tittis", "titty", "tittyfuck", "tittyfucker", "tittys", "tittytwisted", "tittytwister",
                "tittytwisters", "tittytwisting", "tittywank", "titwank", "tity", "tnuc", "to55er", "to55ers",
                "toggaf", "toke", "tongethruster", "tongueina", "tonguethrust", "tonguetramp", "toots", "topless",
                "tortur", "torture", "tosser", "tossers", "tossurs", "towelhead", "trailertrash", "tramp",
                "trannie", "tranny", "transpicuous", "transsexual", "transvestite", "trashy", "tribadism",
                "tribadist", "triplex", "trisexual", "triticum", "trois", "trojan", "trots", "tubgirl", "tuckahoe",
                "tucum", "tunneloflove", "turd", "turd:saturday", "turncock", "turnon", "tush", "tushy", "tvvat",
                "tvvats", "tw_", "tw_nbsp;at", "tw_t", "tw_ts", "tw4t", "twank", "twat", "twat:atwater", "twathead",
                "twatlips", "twats", "twatt", "twattish", "twattle", "twatty", "twatwaffle", "twink", "twinkie",
                "twobitwhore", "twogirlsonecup", "twunt", "twunter", "twunts", "tycoon", "tycoons", "ukrop",
                "unauspicious", "uncircumcise", "uncircumcised", "uncircumcision", "uncircumstantial",
                "uncircumstantialy", "unclefucker", "uncletom", "uncock", "unconspicuous", "uncumber", "uncumbered",
                "undisputable", "undocument", "undocumented", "undressing", "unencumber", "unencumbered", "unfuckable",
                "unincumber", "unincumbered", "unrehearse", "unrehearsed", "unsuspicious", "unsuspiciously",
                "uplaywiddix", "upskirt", "uptheass", "upthebutt", "upthegary", "urethraplay", "urophilia", "usama",
                "ussys", "uzi", "va1jina", "vademecum", "vag", "vag1na", "vagiina", "vagina", "vaginalicker",
                "vaj1na", "vajayjay", "vajina", "valium", "venusmound", "vgra", "viagra", "viaticum", "viaticums",
                "vibr", "vibrater", "vibrator", "vigra", "violetwand", "virgin", "virginbreaker", "vittu", "vixen",
                "vjayjay", "vodka", "vomit", "vorarephilia", "voyeur", "voyeurweb", "voyuer", "vullva", "vulva",
                "w___er", "w_ank", "w_nk", "w_nker", "w_nkers", "w_nks", "w00se", "w0g", "w0gs", "w0p", "w4nker",
                "w4nkers", "wab", "wad", "wang", "wank", "wanka", "wanked", "wanker", "wankers", "wanking",
                "wankjob", "wanks", "wanky", "waysted", "wazoo", "weathercock", "weathercocks", "weenie", "weewee",
                "weiner", "welcher", "welfarerat", "wench", "wetb", "wetback", "wetbacks", "wetdream", "wetspam",
                "wetspot", "wh00r", "wh0re", "whacker", "whackingoff", "whanker", "whankers", "whash", "whigger",
                "whiggers", "whiskeydick", "whiskydick", "whit", "whitenigger", "whitepower", "whites", "whitetrash",
                "whitey", "whiteys", "whities", "whoar", "whop", "whoralicious", "whore", "whorealicious", "whorebag",
                "whored", "whoreface", "whorefucker", "whorehopper", "whorehouse", "whores", "whoring", "wichser",
                "wigga", "wiggas", "wigger", "wiggers", "willie", "willies", "williewanker", "willy", "wiseass",
                "witwatersrand", "wizzer", "wog", "wog:golliwog", "wogs", "womenrapping", "woodcock", "woodcocking",
                "woodcocks", "woose", "wop", "wop_", "words", "worldsex", "wrappingmen", "wrappingtheweasel",
                "wrinkledstarfish", "wristwatch", "wtf", "wuss", "wuzzie", "xkwe", "xrated", "xrse", "xrseh",
                "xrsehol", "xrsehole", "xtc", "xx", "xxx", "xxxhole", "xxxxxx", "y_d", "y_ddo_", "yamashita",
                "yank", "yaoi", "yarpie", "yarpies", "yclit", "yeasty", "yed", "yellowman", "yellowshowers", "yid",
                "yido", "yids", "yiffy", "yobbo", "yourboobs", "yourpenis", "yourtits", "yury", "zabourah",
                "zachariahbishop", "zigabo", "zigabos", "zipperhead", "zipperheads", "zoophile", "zoophilia"
            };
        }
    }
}
